# Generated by Django 2.2.2 on 2019-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильм'},
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='director',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='premiere',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
