# Generated by Django 2.2.2 on 2019-06-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='premiere',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
